#应用环境
spring:
  profiles:
    active: dev
    group:
      "dev":
      "pro":
      "test":
#设置日志模板格式
logging:
  pattern:
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
